"""
Model Paths Manager
Generates module_model_paths.yaml so ComfyUI can find models across
multiple installs and user-added directories.
"""
import re
from pathlib import Path
from typing import Optional

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import (
    COMFYUI_DIR, MODULE_MODEL_PATHS_YAML, MODEL_CATEGORIES,
    get_saved_comfyui_dirs, get_extra_model_dirs,
)


def _safe_key(label: str) -> str:
    """Turn an arbitrary path/label into a valid YAML key."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", label).strip("_")[:60]


def _model_section(base_path: str) -> dict:
    """Build a YAML section dict for a models directory.

    Only includes subdirectories that actually exist on disk.
    """
    section = {"base_path": base_path.replace("\\", "/")}
    bp = Path(base_path)
    for cat in MODEL_CATEGORIES:
        if (bp / cat).is_dir():
            section[cat] = f"{cat}/"
    return section


class ModelPathsManager:
    """Generates and manages the module_model_paths.yaml file."""

    @staticmethod
    def generate_yaml(active_comfyui_dir: Path) -> Optional[Path]:
        """Generate module_model_paths.yaml with cross-references.

        Includes model dirs from all saved ComfyUI installs
        (except the active one) plus user-added extra directories.

        Returns the yaml path if created, or None if no cross-refs needed.
        """
        active_resolved = active_comfyui_dir.resolve()
        sections: dict[str, dict] = {}

        # --- Cross-reference saved ComfyUI installs ---
        for dir_str in get_saved_comfyui_dirs():
            d = Path(dir_str)
            try:
                if d.resolve() == active_resolved:
                    continue  # skip the one we're launching — its models/ is native
            except (OSError, ValueError):
                continue

            models_dir = d / "models"
            if not models_dir.is_dir():
                continue

            key = _safe_key(d.name or d.stem)
            # Ensure unique keys
            if key in sections:
                key = _safe_key(str(d))
            sections[key] = _model_section(str(models_dir))

        # --- The built-in COMFYUI_DIR is always included (if it's not the active one) ---
        try:
            builtin_resolved = COMFYUI_DIR.resolve()
        except (OSError, ValueError):
            builtin_resolved = COMFYUI_DIR

        if builtin_resolved != active_resolved:
            builtin_models = COMFYUI_DIR / "models"
            if builtin_models.is_dir() and "comfyui" not in sections:
                sections["comfy_module_builtin"] = _model_section(str(builtin_models))

        # --- User-added extra model directories ---
        for dir_str in get_extra_model_dirs():
            d = Path(dir_str)
            if not d.is_dir():
                continue
            key = "extra_" + _safe_key(d.name or d.stem)
            if key in sections:
                key = "extra_" + _safe_key(str(d))
            sections[key] = _model_section(str(d))

        # --- Write or clean up ---
        if not sections:
            # No cross-references needed
            if MODULE_MODEL_PATHS_YAML.exists():
                MODULE_MODEL_PATHS_YAML.unlink()
            return None

        lines = ["# Auto-generated by ComfyUI Module -- do not edit manually\n"]
        for section_name, entries in sections.items():
            lines.append(f"{section_name}:")
            for k, v in entries.items():
                lines.append(f"    {k}: {v}")
            lines.append("")

        MODULE_MODEL_PATHS_YAML.write_text("\n".join(lines), encoding="utf-8")
        return MODULE_MODEL_PATHS_YAML
